name: Security check - Bandit
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Security check - Bandit
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab 
      with:
        project_path: .
        ignore_failure: true

