name: DevSecOps

on:
  pull_request:
    types: ['opened']


jobs:

  changelog:

    if: (! github.event.pull_request.draft) && github.head_ref != 'develop'

    defaults:
      run:
        shell: bash

    name: ChangeLOG
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ChangeLOG
        if: ${{ github.head_ref != 'develop' }}
        run:  |
          FILE=$(git diff --name-only origin/develop...HEAD | grep -E 'CHANGELOG\.md' -c)
          if [[ $FILE == "1" ]];
          then
            echo ""
            echo ""
            echo "---------------------------------------------------------------------------"
            echo "-----------------------------Changelog ok!!!-------------------------------"
            echo "---------------------------------------------------------------------------"
            exit 0
          else
            echo ""
            echo ""
            echo "---------------------------------------------------------------------------"
            echo "-----------------------------Add Changelog!!!------------------------------"
            echo "---------------------------------------------------------------------------"
            exit 1
          fi;
       
