name: DevSecOps

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']


jobs:

  changelog:

    if: (! github.event.pull_request.draft) && github.head_ref != 'develop'

    defaults:
      run:
        shell: bash

    name: ChangeLOG
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ChangeLOG
        if: ${{ github.head_ref != 'develop' }}
        run:  |
          FILE=$(git diff --name-only origin/develop...HEAD | grep -E 'CHANGELOG\.md' -c)
          if [[ $FILE == "1" ]];
          then
            echo ""
            cat ./changelog/sucesso
            exit 0
          else
            echo ""
            cat ./changelog/negativo
            echo ""
            echo "---------------------------------------------------------------------------"
            echo "-----------------------------Add Changelog!!!------------------------------"
          fi;
          
  TruffleHog:
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: "*"
          base: develop
          head: HEAD
          extra_args: --debug --only-verified