name: DevSecOps

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']

env:
  MASTER_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
 

jobs:

  changelog:

    if: (! github.event.pull_request.draft) && github.head_ref != 'master' && github.head_ref != 'develop'

    defaults:
      run:
        shell: bash

    name: ChangeLOG
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0



  