name: TruffleHog Secrets Scan
on: [pull_request]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: detect secrets
        uses: trufflesecurity/trufflehog@main
        scanArguments: "--regex --entropy=False --exclude_paths --max_depth=1"