name: security

on: [pull_request]
jobs:
  trufflehog-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # v3
      with:
      fetch-depth: 0
      ref: ${{ github.head_ref }} // necessary for pull request workflow trigger
    - name: trufflehog-actions-scan
      uses: edplato/trufflehog-actions-scan@master
      with:
      scanArguments: "--regex --entropy=False --max_depth=5 --rules /regexes.json" # Add custom options here*



